services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smart_message_manager_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.dev
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://app_user:app_password@mysql:3306/smart_message_manager_db
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    volumes:
      - ./packages/backend/src:/app/packages/backend/src
      - ./packages/models-client:/app/packages/models-client
      - ./packages/models:/app/packages/models
      - /app/packages/backend/node_modules
      - /app/packages/models/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./packages/frontend/src:/app/packages/frontend/src
      - ./packages/models-types:/app/packages/models-types
      - ./packages/frontend/public:/app/packages/frontend/public
      - ./packages/frontend/next.config.ts:/app/packages/frontend/next.config.ts
      - /app/packages/frontend/node_modules
      - /app/packages/frontend/.next
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
